name: Lint project 

on:
  workflow_call:
    inputs:
      RUST_VERSION:
        description: Rust version to use for the workflow
        type: string

      DOCKER_IMAGE:
        description: Docker image to use for the workflow
        type: string

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

      - name: Setup rust environment 
        uses: ./.github/workflows/setup-rust.yml
        with:
          RUST_VERSION: ${{ inputs.RUST_VERSION }} 
      
      - name: Lint Rust code wiht Clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings