name: Lint project 

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: Environment to deploy to
        required: true
        type: string

      RUST_TOOLCHAIN:
        description: Rust toolchain to use for the workflow
        required: true
        type: string

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust environment
        if: inputs.RUST_TOOLCHAIN != 'rust-toolchain.toml'
        run: |
          rustup update
          rustup install ${{ inputs.RUST_TOOLCHAIN }}   
          rustup default ${{ inputs.RUST_TOOLCHAIN }}
          rustup component add clippy
        
      - name: Write toolchain info summary
        run: |
          echo "### Rust version info" >> $GITHUB_SUMMARY
          echo "\`cargo\`:" >> $GITHUB_SUMMARY
          cargo --version --verbose >> $GITHUB_SUMMARY
          echo "\`rustc\`:" >> $GITHUB_SUMMARY
          rustc --version >> $GITHUB_SUMMARY
          echo "\`clippy\`:" >> $GITHUB_SUMMARY
          cargo clippy --version >> $GITHUB_SUMMARY

      - name: Lint Rust code wiht Clippy
        env:
          DEPLOY_ENV: ${{ inputs.DEPLOY_ENV }}
        run: |
          if [[ $DEPLOY_ENV == "PROD" ]]; then
            cargo clippy --all-targets --all-features -- -D warnings
          else
            cargo clippy --all-targets --all-features
          fi