name: Lint project 

on:
  workflow_call:
    inputs:
      DEPLOY_ENV:
        description: Environment to deploy to
        required: true
        type: string

      RUST_TOOLCHAIN:
        description: Rust toolchain to use for the workflow
        required: true
        type: string

jobs:
  lint-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust environment
        env:
          RUST_TOOLCHAIN: ${{ inputs.RUST_TOOLCHAIN }}
        run: |
          rustup update
          if [[ $RUST_TOOLCHAIN != "rust-toolchain.toml" ]]; then
            rustup install ${{ inputs.RUST_TOOLCHAIN }}   
            rustup default ${{ inputs.RUST_TOOLCHAIN }}
          fi
          rustup component add clippy
        
      - name: Write toolchain info summary
        run: |
          echo "### Rust toolchain:
          <table>
            <tr>
              <td>cargo</td>
              <td>$(cargo --version)</td>
            </tr>
            <tr>
              <td>rustc</td>
              <td>$(rustc --version)</td>
            </tr>
            <tr>
              <td>clippy</td>
              <td>$(cargo clippy --version)</td>
            </tr>
          </table>" >> $GITHUB_STEP_SUMMARY

      - name: Lint Rust code wiht Clippy
        env:
          DEPLOY_ENV: ${{ inputs.DEPLOY_ENV }}
        run: |
          if [[ $DEPLOY_ENV == "PROD" ]]; then
            cargo clippy --all-targets --all-features -- -D warnings
          else
            cargo clippy --all-targets --all-features
          fi