name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup enviroment
        run: |
          rustup update
          rustup install nightly   
          rustup component add clippy
          rustup target add wasm32-unknown-unknown
          cargo install --locked cargo-leptos

      - name: Toolchain info 
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version    
          cargo leptos --version

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo leptos test

      - name: Build package
        run: |
          npm install tailwindcss -g
          npx tailwindcss -i style/tailwind.css -o style/generated.css --minify
          cargo leptos build --release


