name: CI

on:
  push:
    branches:
      - master

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup enviroment
        run: |
          rustup update
          rustup install nightly   
          rustup component add clippy
          cargo install --locked cargo-leptos

      - name: Toolchain info 
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version    

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: |
          cargo check
          cargo leptos test --all

      - name: Build package
        run: |
          cargo leptos build


