name: Portfolio CI
on: push
jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: rust-clippy-check
        run: cargo clippy --all-targets --all-features -- -D warnings


