name: Project pipeline

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
        
jobs:
    prepare:
      uses: ./.github/workflows/prepare.yml
      secrets: inherit

    linter:
        uses: ./.github/workflows/linter.yml
        needs: [prepare]
        secrets: inherit
        with:
          RUST_TOOLCHAIN: ${{ needs.prepare.outputs.RUST_TOOLCHAIN }}

    build:
        uses: ./.github/workflows/build.yml
        needs: [prepare, linter]
        secrets: inherit
        with:
          DEPLOY_ENV: ${{ needs.prepare.outputs.DEPLOY_ENV }}
          RUST_TOOLCHAIN: ${{ needs.prepare.outputs.RUST_TOOLCHAIN }}
          IMAGE_NAME: ${{ needs.prepare.outputs.IMAGE_NAME }}

    deploy:
        needs: [prepare, linter, build]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
          DEPLOY_ENV: ${{ needs.prepare.outputs.DEPLOY_ENV }}
          IMAGE_NAME: ${{ needs.prepare.outputs.IMAGE_NAME }}
          DOCKER_IMAGE: ${{ needs.build.outputs.DOCKER_IMAGE }}
