name: Project pipeline

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.githooks/'
      - '.vscode/'
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
        
jobs:
  prepare-pipeline:
    uses: ./.github/workflows/prepare-pipeline.yml
    secrets: inherit

  lint-project:
    uses: ./.github/workflows/lint-project.yml
    needs: [prepare-pipeline]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      RUST_TOOLCHAIN: ${{ needs.prepare-pipeline.outputs.rust_toolchain }}

  version-check:
    uses: ./.github/workflows/version-check.yml
    needs: [prepare-pipeline, lint-project]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      PACKAGE_VERSION: ${{ needs.prepare-pipeline.outputs.package_version }}
      
  release-site:
    uses: ./.github/workflows/release-site.yml
    needs: [prepare-pipeline, version-check]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      PACKAGE_VERSION: ${{ github.sha }}

  build-image:
    uses: ./.github/workflows/build-image.yml
    needs: [prepare-pipeline, version-check]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      RUST_TOOLCHAIN: ${{ needs.prepare-pipeline.outputs.rust_toolchain }}
      IMAGE_NAME: ${{ needs.prepare-pipeline.outputs.image_name }}

  deploy-container:
    uses: ./.github/workflows/deploy-container.yml
    needs: [prepare-pipeline, build-image]
    secrets: inherit
    with:
      DEPLOY_ENV: ${{ needs.prepare-pipeline.outputs.deploy_env }}
      DOCKER_IMAGE: ${{ needs.build-image.outputs.docker_image }}
