name: Pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'CHANGELOG.md'
        
jobs:
    linter:
        uses: .github/workflows/linter.yml
        secrets: inherit

    build:
        uses: .github/workflows/build.yml
        secrets: inherit

    test:
        uses: .github/workflows/test.yml
        secrets: inherit

    deploy:
        needs: [test, linter, build]
        uses: .github/workflows/deploy.yml
        secrets: inherit
