name: Setup rust

on:
  workflow_call:
    inputs: 
      RUST_VERSION:
        description: The version of rust to use
        default: nightly
        type: string
      
      wasm:
        description: Whether to add wasm target
        default: false
        type: boolean

jobs:
  setup-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Rust environment
        run: |
          rustup update
          rustup install ${{ inputs.RUST_VERSION }}   
          rustup default ${{ inputs.RUST_VERSION }}
          rustup component add clippy
        
      - name: Add WASM target
        if: ${{ inputs.wasm }}
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Write toolchain info 
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version    
